name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: ./ReShade.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo and Submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    #- name: Update submodules from origin
    #  run: git submodule update --recursive --remote

    - name: Add Python to PATH
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build 64-Bit
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="64-bit" ${{env.SOLUTION_FILE_PATH}}
    - name: Build 32-Bit
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="32-bit" ${{env.SOLUTION_FILE_PATH}}
    - name: Build Setup
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration="Release Setup" ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Setup EXE
      uses: actions/upload-artifact@v4
      with:
       name: ReShadeSetup
       path: ./bin/AnyCPU/Release/
